Add Dokka plugin to exclude @Internal code from documentation
SpineEventEngine/javadoc-tools pull request #4
Opened 2022-03-31 12:38 UTC by tripolkaandrey

This PR introduces a new module `dokka-extract-internal-plugin`. It is a [custom Dokka plugin](https://kotlin.github.io/dokka/1.6.10/developer_guide/introduction/#building-sample-plugin) to extract from documentation information about the `@Internal` code.

Dokka has several [extension points](https://kotlin.github.io/dokka/1.6.10/developer_guide/extension_points/) at different stages of generating documentation. This new plugin injects a “transformer”(a term native to Dokka) at the stage when all code from source sets was collected and translated to internal Dokka representation [`Documentable`](https://kotlin.github.io/dokka/1.6.10/developer_guide/data_model/#documentable-model). This “transformer” extends class which does all the “messy” job of different processing of modules, packages, types, etc. leaving to us only overwriting the criteria by which we should suppress(exclude) some `Documentable`’s. 

Dokka [automatically loads](https://kotlin.github.io/dokka/1.6.10/developer_guide/introduction/#:~:text=All%20instances%20are%20automatically%20loaded%20during%20Dokka%20setup%20using%20java.util.ServiceLoader) this plugin if it is present on the classpath. If your project already has Dokka, this plugin can be added via 
```build.gradle.kts
dependencies {
    dokkaPlugin("io.spine.tools:spine-dokka-exclude-internal-plugin:${version}")
}
```

This repo is no longer only about `Javadoc` tools. Now it is `doc-tools` because more than one documentation tool is involved. So the REAMDE also was updated.

2022-03-31 14:44 UTC, armiol requested changes
@tripolkaandrey please see my comments.

Most likely, you'll need to browse other Spine modules and projects for the documentation samples. It's going to help you start feeling the style.

2022-03-31 14:44 UTC, armiol commented on dokka-exclude-internal-plugin/build.gradle.kts
> +val dokkaVersion = "1.6.10"
Let's try to use the version declared [here](https://github.com/SpineEventEngine/config/blob/master/buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt). Of course, you'll need to bump it in that repository as well.

2022-03-31 14:44 UTC, armiol commented on dokka-exclude-internal-plugin/src/main/kotlin/io/spine/tools/dokka/plugin/ExcludeInternalPlugin.kt
> + * Dokka has several extensions points at different stages of generating documentation. The plugin
The first paragraph in the documentation of any type or method is a single sentence answering to the question "what this is" or "what it does".

The following paragraphs extend the first paragraph by providing more details on the subject.

Please adjust.

2022-03-31 14:44 UTC, armiol commented on dokka-exclude-internal-plugin/src/main/kotlin/io/spine/tools/dokka/plugin/ExcludeInternalTransformer.kt
> + * This transformer excludes from documentation everything annotated with [Internal].
Let's shorten.

`Excludes from the resulting documentation everything annotated with [Internal]`.

I also wonder if that applies to the packages — in case there is an annotation in the respective `package-info.java`. That would be nice to mention here.

2022-03-31 14:44 UTC, armiol commented on dokka-exclude-internal-plugin/src/main/kotlin/io/spine/tools/dokka/plugin/ExcludeInternalTransformer.kt
> +     * [WithExtraProperties] is a Dokka-interface which adds a map-field for extra properties.
Let's document this particular method first. What it does? 

The text you have here is rather educational, not a documenting one.

2022-03-31 14:44 UTC, armiol commented on dokka-exclude-internal-plugin/src/main/kotlin/io/spine/tools/dokka/plugin/ExcludeInternalTransformer.kt
> +     * We extract from the map-field, which was added by implementing [WithExtraProperties],
Same as above. 

Also, please refrain from using "We"-sentences in the documentation.

2022-03-31 14:44 UTC, armiol commented on dokka-exclude-internal-plugin/src/main/kotlin/io/spine/tools/dokka/plugin/ExcludeInternalTransformer.kt
> +    private object InternalAnnotationCheck {
Let's document this as well.

2022-03-31 14:44 UTC, armiol commented on pom.xml
>  <artifactId>javadoc-tools</artifactId>
Also, this is no longer the `javadoc-tools`. It's now `doc-tools`.

You'll need to update this value in the build scripts first. Then, it's going to be auto-reflected in this file.

2022-04-01 11:58 UTC, tripolkaandrey commented
Close

2022-04-01 11:58 UTC, closed without merging